import type { Universe } from '@/integrations/local/schema-extensions';

export type TermKey =
  | 'scenario' | 'quest' | 'stage' | 'clear' | 'constellation' | 'channel'
  | 'disaster' | 'life_path' | 'prestige' | 'xp' | 'level' | 'system'
  | 'vault' | 'weekly_review' | 'training' | 'dream_board' | 'novel'
  | 'dokkaebi' | 'nebula' | 'oldest_dream' | 'regression' | 'morning_musts'
  | 'penalty_zone' | 'shadow_army' | 'training_ground' | 'title' | 'stories'
  | 'reputation' | 'stat_physical' | 'stat_psyche' | 'stat_intel'
  | 'stat_spiritual' | 'stat_core' | 'stat_craft' | 'hunter_rank' | 'gate_open'
  | 'gate_cleared' | 'monarch' | 'guild' | 'federation';

const BASE_ORV: Record<TermKey, string> = {
  scenario: 'Scenario',
  quest: 'Quest',
  stage: 'Stage',
  clear: 'Clear',
  constellation: 'Constellation',
  channel: 'Channel',
  disaster: 'Disaster',
  life_path: 'Life Path',
  prestige: 'Prestige',
  xp: 'XP',
  level: 'Level',
  system: 'The System',
  vault: 'The Vault',
  weekly_review: 'Chronicle',
  training: 'Training',
  dream_board: 'Dream Board',
  novel: 'The Novel',
  dokkaebi: 'Dokkaebi',
  nebula: 'Nebula',
  oldest_dream: 'The Oldest Dream',
  regression: 'Regression',
  morning_musts: 'Morning Musts',
  penalty_zone: 'Penalty Zone',
  shadow_army: 'Shadow Army',
  training_ground: 'Training Ground',
  title: 'Title',
  stories: 'Stories',
  reputation: 'Stories',
  stat_physical: 'Physical',
  stat_psyche: 'Psyche',
  stat_intel: 'Intel',
  stat_spiritual: 'Spiritual',
  stat_core: 'Core',
  stat_craft: 'Craft',
  hunter_rank: 'Rank',
  gate_open: 'Active',
  gate_cleared: 'Cleared',
  monarch: 'Demon Constellation',
  guild: 'Channel',
  federation: 'Nebula',
};

export const TERM_MAPS: Record<Universe, Record<TermKey, string>> = {
  orv: { ...BASE_ORV },
  solo_leveling: {
    scenario: 'Gate',
    quest: 'Daily Quest',
    stage: 'Floor',
    clear: 'Conquer',
    constellation: 'Senior Hunter',
    channel: 'Guild',
    disaster: 'Raid Boss',
    life_path: 'Hunter Path',
    prestige: 'Job Change',
    xp: 'Magic Power',
    level: 'Hunter Level',
    system: 'The System',
    vault: 'Shadow Library',
    weekly_review: 'Mission Report',
    training: 'Hunter Training Facility',
    dream_board: "Hunter's Will",
    novel: 'Hunter Log',
    dokkaebi: 'Guild Master',
    nebula: 'Hunter Guild Federation',
    oldest_dream: 'The S-Rank Registry',
    regression: 'Job Reset',
    morning_musts: 'Daily Quests',
    penalty_zone: 'Penalty Zone',
    shadow_army: 'Shadow Army',
    training_ground: 'Hunter Training Facility',
    title: 'Hunter Rank',
    stories: 'Reputation',
    reputation: 'Reputation',
    stat_physical: 'STR',
    stat_psyche: 'INT',
    stat_intel: 'PER',
    stat_spiritual: 'Sense',
    stat_core: 'END',
    stat_craft: 'AGI',
    hunter_rank: 'Hunter Rank',
    gate_open: 'GATE OPEN',
    gate_cleared: 'GATE CLEARED',
    monarch: 'Monarch',
    guild: 'Hunter Guild',
    federation: 'Hunter Guild Federation',
  },
  founder: {
    scenario: 'Initiative',
    quest: 'Task',
    stage: 'Milestone',
    clear: 'Ship',
    constellation: 'Advisor',
    channel: 'Team',
    disaster: 'Crisis',
    life_path: 'Vision',
    prestige: 'Reset Cycle',
    xp: 'Momentum',
    level: 'Stage',
    system: 'Co-pilot',
    vault: 'Research Library',
    weekly_review: 'Mission Report',
    training: 'Skill Lab',
    dream_board: 'North Star Board',
    novel: 'Founder Log',
    dokkaebi: 'Lead',
    nebula: 'Alliance',
    oldest_dream: 'Hall of Fame',
    regression: 'Reset',
    morning_musts: 'Daily Priorities',
    penalty_zone: 'Blocked',
    shadow_army: 'Team',
    training_ground: 'Skill Lab',
    title: 'Title',
    stories: 'Credibility',
    reputation: 'Credibility',
    stat_physical: 'Execution',
    stat_psyche: 'Mindset',
    stat_intel: 'Strategy',
    stat_spiritual: 'Purpose',
    stat_core: 'Resilience',
    stat_craft: 'Craft',
    hunter_rank: 'Stage',
    gate_open: 'Active',
    gate_cleared: 'Shipped',
    monarch: 'Blocker',
    guild: 'Team',
    federation: 'Alliance',
  },
};

export const UNIVERSE_META: Record<Universe, { title: string; subtitle: string; accent: string; concepts: string[] }> = {
  orv: {
    title: "OMNISCIENT READER'S VIEWPOINT",
    subtitle: 'The System watches. Constellations guide. Scenarios must be cleared.',
    accent: 'starfield',
    concepts: ['Scenarios', 'Constellations', 'Disasters', 'The Oldest Dream'],
  },
  solo_leveling: {
    title: 'SOLO LEVELING',
    subtitle: 'You are a Hunter. Gates open daily. Dungeons await.',
    accent: 'gate',
    concepts: ['Gates', 'Daily Quests', 'Shadow Army', 'S-Rank Registry'],
  },
  founder: {
    title: 'FOUNDER OS',
    subtitle: 'Build. Research. Ship. Your co-pilot for the founder journey.',
    accent: 'minimal',
    concepts: ['Initiatives', 'Tasks', 'Roadmap', 'Research'],
  },
};

export const UNIVERSE_CARD_STYLES: Record<Universe, string> = {
  orv: 'bg-gradient-to-br from-[#0a0a1a] via-[#12122a] to-[#0a0a1a] border-purple-500/30',
  solo_leveling: 'bg-gradient-to-br from-[#050508] via-[#0a1020] to-[#050510] border-[#00b4ff]/40 shadow-[0_0_20px_rgba(0,180,255,0.15)]',
  founder: 'bg-gradient-to-br from-card to-secondary border-primary/30',
};
